apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-chart
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - secrets://values-secrets.enc.yaml
      - values.yaml
    path: sample-chart
    repoURL: https://github.com/Maurifc/argocd-helm-secrets
    targetRevision: HEAD